[package]
name = "rredis-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
num-bigint = "0.4.6"
rustyline = "15.0"
rustyline-derive = "0.11.0"
crossterm = "0.28"
ratatui = "0.29"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
