[package]
name = "rredis-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
num-bigint = "0.4.6"
rustyline = { version = "15.0.0", features = ["with-file-history"] }
ratatui = "0.30.0"
crossterm = "0.29.0"
socket2 = "0.5"
